[project]
name = "pre-commit-autoupdate-hook"
version = "0.1.0"
requires-python = ">=3.8,<4"
dependencies = ["pre-commit>=3,<4"]

[project.scripts]
pre-commit-autoupdate = "pre_commit_autoupdate_hook.autoupdate:main"

[tool.setuptools.packages.find]
where = ["src"]
